// RTM concept catalog — the 17 labelable structure types
// Each entry defines how the structure is drawn on the chart and
// the default 10-field schema content (prefilled into the form).

export type ConceptType =
  | 'base' | 'supply' | 'demand'
  | 'ftr' | 'flag' | 'flag_limit'
  | 'qm' | 'diamond'
  | 'dbd' | 'rbd' | 'rbr' | 'dbr'
  | 'mpl' | 'bsz'
  | 'sweep' | 'engulf' | 'compression'
  | 'decision_point' | 'liquidity_pool' | 'swing'
  | 'ecp'

export interface ConceptDef {
  type: ConceptType
  label: string
  shortLabel: string
  category: 'zones' | 'patterns' | 'advanced' | 'liquidity' | 'structure'
  // Drawing geometry:
  //   rectangle (zone) | line (level) | point (event) | polyline (multi-leg structure) | arrow (directional marker)
  geometry: 'rectangle' | 'line' | 'point' | 'polyline' | 'arrow'
  color: string
  defaultDirection: 'bullish' | 'bearish' | 'neutral'
  description: string
  // Prefilled 10-field schema (from KB)
  schemaTemplate: {
    definition: string
    purpose: string
    context: string
    whyItForms: string
    identification: string
    commonMistakes: string
    failureConditions: string
    relationships: string
    probabilityContribution: string
    realChartExample: string
  }
}

export const CONCEPTS: ConceptDef[] = [
  {
    type: 'base',
    label: 'Base',
    shortLabel: 'BASE',
    category: 'zones',
    geometry: 'rectangle',
    color: '#8b7226',
    defaultDirection: 'neutral',
    description: 'Compact consolidation at the origin of an impulse; institutional accumulation/distribution footprint.',
    schemaTemplate: {
      definition: 'A compact consolidation of price (1-6 candles, often overlapping) that forms immediately before a strong directional departure.',
      purpose: 'The base is the entry trigger origin. A zone without a preceding base is a level of interest, not a tradeable zone.',
      context: 'Forms at the origin of an impulsive move, never mid-trend. Precedes the departure candle.',
      whyItForms: 'An institution building a position cannot fill it all at once without moving price against itself. It accumulates over time; price compresses during absorption; price departs when accumulation is complete.',
      identification: 'Compact range, at impulse origin, strong departure, breaks structure on own TF, base extremum = proximal line.',
      commonMistakes: 'Marking any consolidation as a base; marking a topping structure as a base; tradeable without departure; wrong proximal line.',
      failureConditions: 'Departure fails to break structure; price returns and breaks proximal; HTF curve shift after base formation.',
      relationships: 'part-of: Supply, Demand; precedes: Engulf, FTR; amplifies: patterns returning to base; confirmed-by: BOS; invalidated-by: Curve shift.',
      probabilityContribution: 'Base alone ~50%; +curve ~62%; +fresh ~70%; +FTR ~78%.',
      realChartExample: 'EURUSD H1: 4-candle base at 1.0820-1.0835, fires up to 1.0855, base holds on retracement.',
    },
  },
  {
    type: 'supply',
    label: 'Supply Zone',
    shortLabel: 'SUPP',
    category: 'zones',
    geometry: 'rectangle',
    color: '#aa4b42',
    defaultDirection: 'bearish',
    description: 'Price band with unfilled institutional sell orders; price tends to react down on contact.',
    schemaTemplate: {
      definition: 'A price band containing unfilled institutional sell orders, left behind after a distribution event.',
      purpose: 'Short setups. Enter short on return to fresh supply aligned with bearish curve.',
      context: 'Forms at the origin of a downward impulse. Located above current price, waiting for retracement.',
      whyItForms: 'Institution distributes a long position; some sell orders rest unfilled at upper end of distribution band; they sit until price returns.',
      identification: 'Sharp downward departure from a base; zone = base; proximal = base high; distal = base low; must be impulsive + BOS + fresh.',
      commonMistakes: 'Marking every pullback; no departure; treating touched zone as fresh; ignoring curve.',
      failureConditions: 'Price closes decisively above proximal line; unfilled inventory absorbed.',
      relationships: 'Mirror of Demand; has Base at origin; amplified by FTR; invalidated by curve shift.',
      probabilityContribution: 'Fresh supply ~50%; +curve ~65%; +FTR+nested ~75%; -10% per touch.',
      realChartExample: 'EURUSD H4: spike 1.1050→1.1120 then collapse to 1.0900. Base 1.1050-1.1120 = supply. Three weeks later retraces to 1.1085, reverses.',
    },
  },
  {
    type: 'demand',
    label: 'Demand Zone',
    shortLabel: 'DEM',
    category: 'zones',
    geometry: 'rectangle',
    color: '#3d8154',
    defaultDirection: 'bullish',
    description: 'Price band with unfilled institutional buy orders; price tends to react up on contact.',
    schemaTemplate: {
      definition: 'A price band containing unfilled institutional buy orders, left behind after an accumulation event.',
      purpose: 'Long setups. Enter long on return to fresh demand aligned with bullish curve.',
      context: 'Forms at the origin of an upward impulse. Located below current price.',
      whyItForms: 'Institution accumulates a long position; some buy orders rest unfilled at lower end; they sit until price returns.',
      identification: 'Sharp upward departure from a base; zone = base; proximal = base low; distal = base high; must be impulsive + BOS + fresh.',
      commonMistakes: 'Marking wicks as zones (need a base); treating touched as fresh; ignoring curve.',
      failureConditions: 'Price closes decisively below proximal line.',
      relationships: 'Mirror of Supply; has Base at origin; amplified by FTR; invalidated by curve shift.',
      probabilityContribution: 'Fresh demand ~50%; +curve ~65%; +FTR+nested ~75%.',
      realChartExample: 'BTC Daily: 4-day base 58k-60k, fires to 70k. Zone 58k-60k. Retraces to 60.5k, bounces 15%.',
    },
  },
  {
    type: 'ftr',
    label: 'Failure To Return',
    shortLabel: 'FTR',
    category: 'patterns',
    geometry: 'line',
    color: '#4eadcd',
    defaultDirection: 'neutral',
    description: 'After strong departure, price fails to return to base origin; confirms institutional intent.',
    schemaTemplate: {
      definition: 'After a strong departure from a base, price fails to return to the base origin. Indicates no opposing interest.',
      purpose: 'Probability amplifier. FTR-confirmed zones are significantly more likely to react on next return.',
      context: 'Assessed immediately after departure. The longer the non-return, the stronger the FTR.',
      whyItForms: 'Institutional departure exhausted all opposing liquidity at base. No reason to return.',
      identification: 'After base+impulse, check if price returned to base distal. No return = FTR. Strong = <38% retracement.',
      commonMistakes: 'Treating any non-return as FTR (need strong departure); ignoring depth of return; treating as permanent.',
      failureConditions: 'Price returns and breaks base distal; institutional intent changed.',
      relationships: 'Amplifies Zone Quality; created by strong Departure; preserved by Curve; broken by HTF CHoCH.',
      probabilityContribution: 'Strong FTR +15%; moderate +8%; weak +3%; broken -10%.',
      realChartExample: 'GBPUSD H4: base 1.2600-1.2630, departure to 1.2780, retracement to 1.2700 (38%). FTR confirmed.',
    },
  },
  {
    type: 'flag',
    label: 'Flag',
    shortLabel: 'FLAG',
    category: 'patterns',
    geometry: 'rectangle',
    color: '#887246',
    defaultDirection: 'neutral',
    description: 'Short counter-trend consolidation after an impulse; continuation pattern.',
    schemaTemplate: {
      definition: 'A short counter-trend consolidation after an impulse. Continuation pattern, not reversal.',
      purpose: 'Second-entry location in a trend. FL is the deepest point (in trend direction) = reaction level.',
      context: 'After impulse, before next impulse. Typically 3-8 candles; deeper = reversal risk.',
      whyItForms: 'Profit-taking and counter-trend participants create temporary counter-flow. Institution absorbs without breaking structure.',
      identification: 'Preceded by impulse; shallow retracement (38-50%); overlapping ranges; FL = deepest point in trend direction.',
      commonMistakes: 'Treating any pullback as flag; entering wrong end; treating deep retracements (>62%) as flags.',
      failureConditions: 'Price breaks FL decisively. "Flag" was first leg of reversal.',
      relationships: 'Continuation Pattern; FL is reaction level; Flag+Compression = high-prob continuation; Flag failure = early CHoCH.',
      probabilityContribution: 'Flag at FL+curve ~65%; +compression ~72%; without impulse ~45%.',
      realChartExample: 'ES H1: impulse 4500→4540, pullback to 4524 (40%). FL=4524. Next pullback to 4524 bounces.',
    },
  },
  {
    type: 'flag_limit',
    label: 'Flag Limit',
    shortLabel: 'FL',
    category: 'patterns',
    geometry: 'line',
    color: '#5d7d9d',
    defaultDirection: 'neutral',
    description: 'Boundary of a flag beyond which prior impulse intent is invalidated; high-probability reaction level.',
    schemaTemplate: {
      definition: 'The boundary of a flag beyond which prior impulse intent is invalidated. Deepest point of flag in trend direction.',
      purpose: 'FLs are gravity wells. Once formed, price tends to react there on future approaches — even weeks later.',
      context: 'Forms at end of flags. Wick or body extreme of deepest candle. HTF FLs dominate LTF FLs.',
      whyItForms: 'FL is where institutional absorption was strongest during flag. Orders rest there; level becomes magnet.',
      identification: 'After impulse+flag, identify deepest point in trend direction. Mark it. Monitor for future reactions.',
      commonMistakes: 'Marking every minor pullback low as FL; ignoring broken FLs (still residual); treating FLs as standalone zones.',
      failureConditions: 'FL fails when price decisively breaks AND closes beyond. Residual reaction probability drops.',
      relationships: 'Reaction level inside Flag; FL+Zone = high-prob entry; component of Decision Points; HTF overrides LTF.',
      probabilityContribution: 'FL alone ~55%; +Zone ~72%; +Zone+Curve ~78%.',
      realChartExample: 'EURUSD H4: impulse 1.0800→1.0940, flag to 1.0870 (FL). 3 weeks later retraces to 1.0870, bounces.',
    },
  },
  {
    type: 'qm',
    label: 'Quasimodo',
    shortLabel: 'QM',
    category: 'advanced',
    geometry: 'polyline',
    color: '#9333ea',
    defaultDirection: 'neutral',
    description: 'Reversal structure: left shoulder, head (sweep), BOS, return to shoulder, entry.',
    schemaTemplate: {
      definition: 'Reversal structure with 5 components: left shoulder, lower high (or higher low), head (sweep), BOS, return to shoulder, entry.',
      purpose: 'Highest-probability reversal setup. Captures exact moment IPDA finishes liquidity sweep and reverses.',
      context: 'End of extended trend, after liquidity sweep. Valid on all TFs but only tradeable when HTF-curve aligned.',
      whyItForms: 'IPDA sweeps liquidity beyond obvious swing (head), then reverses. Shoulder is prior swing violated; return to shoulder is IPDA re-entering reversal.',
      identification: '5 components in sequence: prior trend, left shoulder, head (sweep), BOS (CHoCH), return to shoulder.',
      commonMistakes: 'Marking QM without clear sweep; entering before BOS; treating head as entry; ignoring HTF curve.',
      failureConditions: 'Price returns to shoulder and breaks it (instead of reacting). Intent shift was fake.',
      relationships: 'Reversal Pattern; requires Sweep at head; confirmed by CHoCH; entry at shoulder=prior Swing; amplified by Curve+Nesting.',
      probabilityContribution: 'QM+sweep+CHoCH+curve ~75%; +Decision Point ~82%; counter-curve ~35% (skip).',
      realChartExample: 'EURUSD H1: LH at 1.0920 (shoulder), head at 1.0950 (sweep of 1.0940 BSL), CHoCH below 1.0900, return to 1.0920 → short.',
    },
  },
  {
    type: 'diamond',
    label: 'Diamond',
    shortLabel: 'DIA',
    category: 'advanced',
    geometry: 'polyline',
    color: '#7c3aed',
    defaultDirection: 'neutral',
    description: 'Symmetric reversal structure: impulse, shallow counter-move, continuation that fails and reverses.',
    schemaTemplate: {
      definition: 'Symmetric reversal: impulse, shallow counter-move (diamond — symmetric consolidation), then continuation that fails and reverses.',
      purpose: 'High-probability reversal, rarer than QM but cleaner. Symmetry is the tell — distribution mimicking continuation.',
      context: 'End of extended trend. Diamond is 5-10 candles of symmetric consolidation after impulse.',
      whyItForms: 'Institution distributes/accumulates into latecomers chasing the impulse. Symmetric consolidation = absorption; reversal = commitment.',
      identification: 'Extended prior trend; impulse; symmetric consolidation 5-10 candles; break in opposite direction of impulse with strength.',
      commonMistakes: 'Treating any consolidation as diamond (need symmetry); entering before break; ignoring prior trend; treating trend-direction break as continuation.',
      failureConditions: 'Price breaks diamond in trend direction with strength. Apparent distribution was real continuation.',
      relationships: 'Reversal Pattern; similar to Compression but symmetric; confirmed by BOS in reversal direction; amplified by Curve+Sweep prior.',
      probabilityContribution: 'Diamond+curve+sweep ~72%; without HTF confirmation ~50%; trend-direction break = continuation.',
      realChartExample: 'EURUSD H4: uptrend to 1.1100, impulse 1.1050→1.1100, 7-candle symmetric diamond 1.1075-1.1100, break below with engulf.',
    },
  },
  {
    type: 'dbd',
    label: 'DBD (Demand-Based Drawdown)',
    shortLabel: 'DBD',
    category: 'advanced',
    geometry: 'polyline',
    color: '#6366f1',
    defaultDirection: 'bullish',
    description: 'Drawdown structure that originates from a demand base — institutional accumulation footprint during a pullback.',
    schemaTemplate: {
      definition: 'A pullback or retracement whose origin is a demand base. The drawdown terminates at the demand zone, signaling continuation upward.',
      purpose: 'Continuation entry. DBD marks where institutional buyers re-enter during a pullback, providing a high-probability long setup.',
      context: 'Forms during a retracement in an uptrend, terminating at a prior demand zone or base.',
      whyItForms: 'Institutions that built positions at the demand base defend that level on retracement. The drawdown stops where their orders rest.',
      identification: 'Uptrend → pullback → terminates at prior demand zone with reaction (wick, engulf, compression). Mark the drawdown range from swing high to demand reaction.',
      commonMistakes: 'Marking any pullback as DBD without demand confirmation; entering before reaction signal; ignoring HTF curve alignment.',
      failureConditions: 'Price decisively breaks below the demand zone. The "DBD" was actually a reversal in progress.',
      relationships: 'Continuation Pattern; requires Demand Zone at termination; confirmed by reaction signal; amplified by HTF alignment.',
      probabilityContribution: 'DBD+demand+curve ~68%; +reaction signal ~75%; counter-curve ~40%.',
      realChartExample: 'EURUSD H1: uptrend 1.0800→1.0920, pullback to 1.0850 demand zone, bullish engulf → continuation to 1.0960.',
    },
  },
  {
    type: 'rbd',
    label: 'RBD (Risk-Based Demand)',
    shortLabel: 'RBD',
    category: 'advanced',
    geometry: 'polyline',
    color: '#0ea5e9',
    defaultDirection: 'bullish',
    description: 'Demand zone where institutional risk was defined — origin of a risk-based move with defended orders.',
    schemaTemplate: {
      definition: 'A demand zone that originates from a risk-based institutional position. The base shows absorption before a strong bullish departure.',
      purpose: 'High-probability long entry. RBD zones are defended because institutions have risk defined at that level.',
      context: 'Forms at the origin of a strong bullish impulse, where institutional risk limits were set.',
      whyItForms: 'Institutions set risk (stop-loss) at the base of their position. If price returns, they defend to avoid being stopped out at a loss.',
      identification: 'Strong bullish impulse from compact base; base = demand zone; on retracement, price reacts at proximal line.',
      commonMistakes: 'Marking weak bases as RBD; entering without reaction confirmation; ignoring fresh vs touched status.',
      failureConditions: 'Price closes below the base proximal line. Risk was invalidated.',
      relationships: 'Type of Demand Zone; has Base at origin; amplified by FTR; confirmed by reaction on retracement.',
      probabilityContribution: 'RBD fresh ~60%; +curve ~72%; +FTR ~78%; -10% per touch.',
      realChartExample: 'GBPUSD H4: base 1.2600-1.2620, impulse to 1.2720. Retracement to 1.2625 reacts, continuation to 1.2800.',
    },
  },
  {
    type: 'rbr',
    label: 'RBR (Risk-Based Reversal)',
    shortLabel: 'RBR',
    category: 'advanced',
    geometry: 'polyline',
    color: '#f59e0b',
    defaultDirection: 'neutral',
    description: 'Reversal structure originating from a risk-based zone — where institutional risk defense triggers the reversal.',
    schemaTemplate: {
      definition: 'A reversal that occurs at a risk-based zone (RBD or RBS). The zone is tested, defended, and price reverses with intent shift.',
      purpose: 'Reversal entry. RBR combines zone quality with institutional risk defense — highest-probability reversal setup.',
      context: 'Forms when price returns to a risk-based zone and the zone holds, triggering BOS in the opposite direction.',
      whyItForms: 'Institutions defending their risk at the zone cause absorption. When sellers/buyers are exhausted, price reverses with intent shift.',
      identification: 'Identify RBD/RBS zone → price returns → reaction (wick, compression) → BOS/CHoCH in reversal direction → enter on retest.',
      commonMistakes: 'Entering before BOS confirmation; treating any zone reaction as RBR; ignoring HTF curve; entering against curve.',
      failureConditions: 'Zone breaks decisively. The "reversal" was a continuation through the zone.',
      relationships: 'Reversal Pattern; requires RBD/RBS at origin; confirmed by BOS; amplified by Curve+Sweep; entry on retest.',
      probabilityContribution: 'RBR+zone+curve+BOS ~75%; +sweep prior ~82%; counter-curve ~35% (skip).',
      realChartExample: 'EURUSD H1: RBD at 1.0850, price retraces, wicks at 1.0855, BOS above 1.0880 → long on retest to 1.0920.',
    },
  },
  {
    type: 'dbr',
    label: 'DBR (Demand-Based Reversal)',
    shortLabel: 'DBR',
    category: 'advanced',
    geometry: 'polyline',
    color: '#14b8a6',
    defaultDirection: 'bullish',
    description: 'Reversal that occurs at a demand zone — price returns to demand, reacts, and reverses bullish.',
    schemaTemplate: {
      definition: 'A bullish reversal that occurs when price returns to a demand zone, reacts, and reverses direction with a BOS.',
      purpose: 'Reversal long entry. DBR is the demand-side counterpart to RBR, focused on demand zone quality.',
      context: 'Forms at a fresh demand zone during a downtrend. The zone holds, causing intent shift bullish.',
      whyItForms: 'Unfilled buy orders at the demand zone absorb sellers. Once selling pressure is exhausted, price reverses.',
      identification: 'Fresh demand zone → price returns → reaction (bullish engulf, wick, compression) → BOS bullish → enter on retest.',
      commonMistakes: 'Marking DBR without fresh demand; entering before BOS; ignoring HTF curve; treating touched zones as fresh.',
      failureConditions: 'Demand zone breaks decisively. Reversal was continuation.',
      relationships: 'Reversal Pattern; requires Demand Zone; confirmed by BOS; amplified by Curve+Sweep; mirror of SBS.',
      probabilityContribution: 'DBR+demand+curve+BOS ~72%; +sweep prior ~80%; counter-curve ~38%.',
      realChartExample: 'EURUSD H4: demand 1.0800-1.0820, price retraces, wicks at 1.0810, BOS above 1.0850 → long on retest to 1.0920.',
    },
  },
  {
    type: 'mpl',
    label: 'MPL (Max Pain Line)',
    shortLabel: 'MPL',
    category: 'liquidity',
    geometry: 'line',
    color: '#dc2626',
    defaultDirection: 'neutral',
    description: 'Price level with most resting orders; major unswept swing. IPDA target for liquidity.',
    schemaTemplate: {
      definition: 'The price level where the most resting orders sit, typically a prior swing high/low that has not yet been swept.',
      purpose: 'MPL is a TARGET, not an entry. Used as take-profit for trades in its direction.',
      context: 'Typically a major HTF swing that has not been swept since formation. The longer unswept, the more significant.',
      whyItForms: 'Unswept major swings accumulate stops over time. As price moves away and retail enters trend, stops cluster beyond swing.',
      identification: 'On HTF, identify major swings NOT swept since formation. Most significant (oldest + most obvious) = MPL.',
      commonMistakes: 'Treating every swing as MPL; treating MPL as entry (it is a target); ignoring MPL after sweep (find next one).',
      failureConditions: 'MPL "consumed" when swept. After sweep, may still react but with much lower probability.',
      relationships: 'Liquidity concept (HTF Liquidity Pool); target for trades; often QM head; full trade plan = entry zone + target MPL + curve direction.',
      probabilityContribution: 'MPL as target ~70% hit rate; MPL as entry (after sweep+reversal) ~65%.',
      realChartExample: 'EURUSD Weekly: prior swing high 1.1275 from 8 months ago, unswept. Daily long entry at 1.0900, target 1.1275.',
    },
  },
  {
    type: 'bsz',
    label: 'BSZ',
    shortLabel: 'BSZ',
    category: 'liquidity',
    geometry: 'line',
    color: '#ea580c',
    defaultDirection: 'neutral',
    description: 'Base & Solid Zone (confirmed zone) OR Buy-Side Zone (liquidity above swings).',
    schemaTemplate: {
      definition: 'Two usages: (a) Base & Solid Zone — zone confirmed by multiple reactions; (b) Buy-Side Zone — zone above current price where buy stops rest.',
      purpose: 'BSZ (Base & Solid): priority reaction level. BSZ (Buy-Side): target for bullish moves; potential reversal after sweep.',
      context: 'BSZ (B&S) forms after zone reacts 2+ times with strong departures. BSZ (Buy-Side) is any level above current price where buy stops rest.',
      whyItForms: 'B&S: each reaction confirms inventory. Buy-Side: buy stops cluster beyond obvious swing highs.',
      identification: 'B&S: zone reacted 2+ times with strong departures. Buy-Side: level above current price beyond prior swing highs.',
      commonMistakes: 'Confusing the two meanings; treating buy-side zone as long entry (it is a target); treating B&S as fresh (it is consumed).',
      failureConditions: 'B&S fails when price breaks zone decisively. Buy-Side fails (as reversal) when price sweeps and continues.',
      relationships: 'Buy-Side = Liquidity Pool; B&S = quality designation; Buy-Side+Sweep = QM head candidate; B&S = Decision Point component.',
      probabilityContribution: 'B&S as reaction ~65% (despite consumption); Buy-Side as target ~70%; Buy-Side+Sweep+Reversal ~68%.',
      realChartExample: 'EURUSD H1: supply 1.0940-1.0960 reacted 3 times with strong bearish departures = BSZ. Or prior H4 swing high 1.1020 unswept = Buy-Side Zone target.',
    },
  },
  {
    type: 'sweep',
    label: 'Sweep',
    shortLabel: 'SWP',
    category: 'liquidity',
    geometry: 'point',
    color: '#dc2626',
    defaultDirection: 'neutral',
    description: 'Quick move beyond liquidity pool that immediately reverses; stop hunt signature.',
    schemaTemplate: {
      definition: 'Quick move beyond a liquidity pool that immediately reverses. Visible signature of stop hunt.',
      purpose: 'Highest-probability reversal triggers. Enter on reversal with tight invalidation (beyond sweep extreme).',
      context: 'At liquidity pools on every TF. Most significant at HTF pools (Daily, Weekly).',
      whyItForms: 'IPDA pushes price beyond pool to fill orders against stops, then immediately reverses to deliver true move.',
      identification: 'Obvious liquidity pool; quick move beyond (often single candle, wick beyond); immediate reversal with strength.',
      commonMistakes: 'Treating every wick beyond swing as sweep (need immediate reversal); entering before reversal confirms; ignoring HTF curve.',
      failureConditions: 'Sweep fails when price does not reverse — move beyond pool was real continuation.',
      relationships: 'Visible event of Stop Hunt; head of QM; Sweep+CHoCH = high-prob reversal; Sweep that fails = real continuation (treat as BOS).',
      probabilityContribution: 'Sweep+reversal+CHoCH+curve ~75%; alone ~50%; counter-curve ~35%.',
      realChartExample: 'BTC H4: swing high 73000. Single H4 candle to 73500 (sweep), immediate bearish engulf, closes 70000. Counter-curve if H4 bullish — skip.',
    },
  },
  {
    type: 'engulf',
    label: 'Engulf',
    shortLabel: 'ENG',
    category: 'patterns',
    geometry: 'arrow',
    color: '#16a34a',
    defaultDirection: 'neutral',
    description: 'Candle whose body fully covers prior candle body in opposite direction; institutional commitment signature. Click above a candle for a down-arrow at its high, or below for an up-arrow at its low.',
    schemaTemplate: {
      definition: 'Candle whose body fully covers prior candle body in opposite direction. Signature of institutional commitment after event.',
      purpose: 'Entry trigger. Enter on engulf close at zone reaction; without engulf, reaction is unconfirmed.',
      context: 'At zone reactions, compression resolves, flag limits, sweep reversals. Location determines significance.',
      whyItForms: 'Institution becomes dominant aggressor in opposite direction of prior candle. Prior candle = one side aggression; engulf = opposing side overwhelmed.',
      identification: 'Prior candle has clear body; engulf body fully covers prior body in opposite direction; engulf closes near extremum.',
      commonMistakes: 'Treating range-coverage (including wicks) as engulf (must cover body); entering every engulf regardless of location; ignoring body proportion.',
      failureConditions: 'Engulf fails when next candle reclaims ≥50% of engulf range. Institutional commitment was fake.',
      relationships: 'Resolve of Compression; entry trigger at Zone reactions; confirms Sweep reversals; amplified at Decision Points; common BOS candle.',
      probabilityContribution: 'Engulf at fresh zone+curve ~72%; at decision point ~80%; in no-man\'s land ~50% (do not trade).',
      realChartExample: 'BTC H1: demand 60000-60500. Prior candle small bearish 60800→60650. Next candle 60600→61200, body covers prior, breaks 61000 swing. Bullish engulf.',
    },
  },
  {
    type: 'compression',
    label: 'Compression',
    shortLabel: 'CMP',
    category: 'patterns',
    geometry: 'rectangle',
    color: '#0891b2',
    defaultDirection: 'neutral',
    description: 'Tight consolidation of overlapping candles with diminishing range; institutional accumulation in progress.',
    schemaTemplate: {
      definition: 'Tight consolidation of overlapping candles with diminishing range. Footprint of institutional accumulation/distribution in progress.',
      purpose: 'Forward-looking signal: longer/tighter compression = more violent eventual resolve. Do not trade inside; prepare to trade breakout.',
      context: 'Reversal compressions at zones; continuation compressions at flags. 4-6+ candles required.',
      whyItForms: 'Institution absorbing opposing flow without showing hand. As accumulation progresses, opposing flow diminishes, ranges contract.',
      identification: 'Overlapping candle ranges; diminishing ATR; at least 4-6 candles. Longer = stronger resolve.',
      commonMistakes: 'Treating any small-candle pause as compression; trading inside; assuming compression always breaks in trend direction.',
      failureConditions: 'Compression extends too long without resolving (>20 candles). Institutional intent has likely changed.',
      relationships: 'Precedes Engulf (resolve is often engulf); often inside Base; at FL = high-prob continuation; at zone = high-prob reversal.',
      probabilityContribution: 'Compression+curve ~70%; against curve ~40%; length positively correlated with resolve strength.',
      realChartExample: 'EURUSD H1: up-move to 1.0950, 6-candle compression 1.0935-1.0950 at supply. Breaks below 1.0935 with engulf, drops to 1.0880.',
    },
  },
  {
    type: 'decision_point',
    label: 'Decision Point',
    shortLabel: 'DP',
    category: 'structure',
    geometry: 'line',
    color: '#9333ea',
    defaultDirection: 'neutral',
    description: 'Price level where multiple structures converge — zone, swing, FL — forcing IPDA decision.',
    schemaTemplate: {
      definition: 'Price level where multiple structures converge — zone, swing, FL, HTF zone edge — forcing IPDA decision.',
      purpose: 'Highest-probability trade locations. Convergence amplifies reaction probability multiplicatively.',
      context: 'Identified by overlaying multiple structure types. Where 3+ structures cluster within tight price band (<0.2% wide).',
      whyItForms: 'Each structure = independent institutional interest. Multiple institutions forced to act simultaneously → outsized reaction.',
      identification: 'Mark all zones, swings, FLs, HTF zone edges. Look for 3+ clusters within tight band.',
      commonMistakes: 'Counting same structure twice; treating 2-point convergence as DP (need 3+); ignoring time (2-year-old DP less relevant).',
      failureConditions: 'DP fails when one component is invalidated (e.g., zone consumed and broken). Convergence loses force with each failed component.',
      relationships: 'Convergence of Zone, Swing, FL, HTF Zone; amplifies every pattern; highest-quality input to Zone Quality scoring.',
      probabilityContribution: 'DP (3+ structures) +20%; 5+ structures +30%. Highest-probability trade locations in RTM.',
      realChartExample: 'GBPUSD H1 at 1.2680: H1 demand edge + H4 swing low + FL + Daily demand proximal. Four structures = DP.',
    },
  },
  {
    type: 'liquidity_pool',
    label: 'Liquidity Pool',
    shortLabel: 'LIQ',
    category: 'liquidity',
    geometry: 'line',
    color: '#dc2626',
    defaultDirection: 'neutral',
    description: 'Concentration of resting orders at specific price level; IPDA target.',
    schemaTemplate: {
      definition: 'Concentration of resting orders at specific price level. IPDA targets pools when it needs liquidity.',
      purpose: 'Identifying pools allows predicting IPDA next move. Buy-side above swing highs; sell-side below swing lows.',
      context: 'Form beyond obvious swing highs (buy-side) and below obvious swing lows (sell-side). Size scales with obviousness and time since swept.',
      whyItForms: 'Retail stop-placement is predictable. Stops cluster beyond obvious swings; the more obvious, the larger the pool.',
      identification: 'Identify obvious unswept swing highs (buy-side) and lows (sell-side). More obvious + unswept = larger pool.',
      commonMistakes: 'Treating every swing as a pool; treating swept pool as active; ignoring time dimension (pools grow over time).',
      failureConditions: 'Pool consumed when swept. After sweep, pool empty until new stops accumulate (days/weeks on H1, weeks/months on Daily).',
      relationships: 'Specific locations of Liquidity; Stop Hunts sweep them; MPL = highest-TF pool; Sweeps are events of visiting pools.',
      probabilityContribution: 'Trades targeting pool ~70% hit rate; reversals after pool sweep ~65%.',
      realChartExample: 'GBPUSD H1: obvious swing high 1.2785 (4 touches over 3 days). Price pushes to 1.2790 (sweep), reverses.',
    },
  },
  {
    type: 'swing',
    label: 'Swing',
    shortLabel: 'SWG',
    category: 'structure',
    geometry: 'line',
    color: '#534c34',
    defaultDirection: 'neutral',
    description: 'Pivot point where price reversed; atomic unit of structure.',
    schemaTemplate: {
      definition: 'Pivot point where price reversed direction. Swing high = peak followed by lower high; swing low = trough followed by higher low.',
      purpose: 'Swings define levels that must be broken for structure to continue or shift. Also most common location of liquidity.',
      context: 'A swing requires 2-3 candles of counter-move on each side. Single-candle spike is not a swing. HTF swings dominate LTF.',
      whyItForms: 'Swing high forms when buying pressure exhausts at price where sellers were waiting. Swing low forms symmetrically.',
      identification: 'Requires 2-3 candles of counter-move on each side. Extremum (wick or body) = level. Body-based on LTF, wick-based on HTF.',
      commonMistakes: 'Marking every wick as swing; failing to require confirmation; treating inside bars as swings; mixing wick/body conventions.',
      failureConditions: 'Swing invalidated only when price closes decisively beyond AND close holds. Wick beyond = sweep, not structural break.',
      relationships: 'Define BOS and CHoCH; where liquidity pools form; proximal/distal anchors of zones; curve = longest swing sequence.',
      probabilityContribution: 'Swings alone are descriptive. Contribution comes from being broken (BOS) or swept (liquidity event).',
      realChartExample: 'GBPUSD H4: peaks at 1.2785, retraces 4 candles to 1.2720, advances. 1.2785 = confirmed swing high.',
    },
  },
  {
    type: 'ecp',
    label: 'ECP (Extended Correction Point)',
    shortLabel: 'ECP',
    category: 'structure',
    geometry: 'line',
    color: '#7c3aed',
    defaultDirection: 'neutral',
    description: 'Extended correction point — a deep or prolonged retracement level where structure forces a decision.',
    schemaTemplate: {
      definition: 'A retracement level where correction extends beyond normal bounds (deeper than 62% or longer in time), forcing an IPDA decision point.',
      purpose: 'Marks high-stakes decision zones. Extended corrections often precede either trend resumption or full reversal.',
      context: 'Forms during a retracement that exceeds normal parameters. The longer/deeper the correction, the more significant the ECP.',
      whyItForms: 'When a retracement extends beyond normal, institutions are re-evaluating intent. The ECP is where the decision crystallizes.',
      identification: 'Retracement >62% Fibonacci OR time-equivalent to prior leg. Mark the extreme of the correction as the ECP line.',
      commonMistakes: 'Marking normal retracements as ECP; entering without confirmation signal; ignoring HTF structure context.',
      failureConditions: 'Price decisively breaks beyond ECP with continuation. The "correction" was actually a reversal.',
      relationships: 'Type of Decision Point; amplified by zone confluence; confirmed by reaction signal; HTF ECPs dominate LTF.',
      probabilityContribution: 'ECP+zone+curve ~65%; +reaction signal ~72%; without HTF context ~45%.',
      realChartExample: 'EURUSD H4: uptrend 1.0800→1.0950, retracement extends to 1.0820 (76% Fib, time = prior leg). ECP at 1.0820, reaction → continuation.',
    },
  },
]

export const CONCEPT_MAP: Record<ConceptType, ConceptDef> = CONCEPTS.reduce(
  (acc, c) => { acc[c.type] = c; return acc },
  {} as Record<ConceptType, ConceptDef>,
)

export const CATEGORY_LABELS: Record<string, string> = {
  zones: 'Zones',
  patterns: 'Patterns',
  advanced: 'Advanced Patterns',
  liquidity: 'Liquidity',
  structure: 'Structure',
}
